In [ ]:
import tensorflow_datasets as tfds

imdb, info = tfds.load('imdb_reviews', with_info=True, as_supervised = True)

In [ ]:
import numpy as np
train_data, test_data = imdb['train'], imdb['test']
train_sentences = []
test_sentences = []
train_labels = []
test_labels = []

In [ ]:
first_element = next(iter(train_data.take(1)))
print(first_element)

(<tf.Tensor: shape=(), dtype=string, numpy=b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.">, <tf.Tensor: shape=(), dtype=int64, numpy=0>)


In [ ]:
for s,l in train_data:
  # print(s)
  train_sentences.append(str(s.numpy()))
  # print(l)
  train_labels.append(l.numpy())
  # break

for s,l in test_data:
  test_sentences.append(str(s.numpy()))
  test_labels.append(l.numpy())

In [ ]:
train_sentences.append(str('phuc'))

In [ ]:
print(train_sentences[0])
print(train_labels[0])

b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it."
0


In [ ]:
train_labels = np.array(train_labels)
test_labels = np.array(test_labels)

In [ ]:
vocab_size = 10000
embedding = 64
max_length = 140

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
tokenizer = Tokenizer (num_words=vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts (train_sentences)

In [ ]:
tokenizer.word_index
train_sentences = tokenizer.texts_to_sequences(train_sentences)
padded_train_sentences = pad_sequences (train_sentences, maxlen=max_length, truncating='post', padding='post')

In [ ]:
test_sentences = tokenizer.texts_to_sequences (test_sentences)
padded_test_sentences = pad_sequences(test_sentences, maxlen=max_length, truncating='post', padding='post')

In [ ]:
padded_train_sentences

array([[  59,   12,   14, ...,    0,    0,    0],
       [ 256,   28,   78, ...,    0,    0,    0],
       [   1, 6175,    2, ...,    0,    0,    0],
       ...,
       [2677,   11,  216, ..., 1048,   37,   31],
       [3875,    5,   31, ...,    1, 2238,   42],
       [   1,    0,    0, ...,    0,    0,    0]], dtype=int32)

In [ ]:
print(vocab_size)

10000


In [ ]:
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import SimpleRNN, Dense

# model = Sequential()
# model.add(Embedding(vocab_size, 64, input_length=max_length))
# model.add(SimpleRNN(units=512, input_shape=(max_length, vocab_size)))
# model.add(Dense(128, activation='relu'))
# model.add(Dense(1, activation='sigmoid'))
# model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# model.summary()

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, LSTM, Bidirectional, Dense, Flatten
model = Sequential()
model.add(Embedding(vocab_size, embedding, input_length = max_length))
model.add(Flatten())
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
model.summary()

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_7 (Embedding)     (None, 140, 64)           640000    
                                                                 
 flatten_5 (Flatten)         (None, 8960)              0         
                                                                 
 dense_22 (Dense)            (None, 10)                89610     
                                                                 
 dense_23 (Dense)            (None, 1)                 11        
                                                                 
Total params: 729621 (2.78 MB)
Trainable params: 729621 (2.78 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.fit(padded_train_sentences[:-1], train_labels, epochs=10, validation_data= (padded_test_sentences, test_labels))

Epoch 1/10
782/782 [==============================] - 547s 593ms/step - loss: 0.7660 - acc: 0.5004 - val_loss: 0.7046 - val_acc: 0.4986
Epoch 2/10
782/782 [==============================] - 405s 518ms/step - loss: 0.7116 - acc: 0.4949 - val_loss: 0.6974 - val_acc: 0.5000
Epoch 3/10
464/782 [================>.............] - ETA: 2:08 - loss: 0.7022 - acc: 0.5039

In [ ]:
test_sen = ['i hate this movie']
test_seq = tokenizer.texts_to_sequences (test_sen)
padded_test_seq=pad_sequences(test_seq, maxlen = max_length, truncating='post', padding='post')
padded_test_seq

array([[ 11, 797,  12,  18,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0]], dtype=int32)

In [ ]:
model.predict(padded_test_seq)

1/1 [==============================] - 0s 112ms/step


array([[0.2977786]], dtype=float32)

In [ ]:
e = model.layers[0]
print(e)
weights = e.get_weights()[0]
print(weights.shape)
print(weights)

(10000, 64)
[[-0.00608895 -0.00754182  0.0354711  ...  0.02131607 -0.01723441
   0.00037165]
 [-0.02560235  0.011722    0.02681784 ... -0.01761917  0.0136407
  -0.01606897]
 [-0.02922298 -0.02853404 -0.00201035 ...  0.01685899 -0.02187564
  -0.02779569]
 ...
 [ 0.02215918 -0.06712981  0.07243536 ...  0.05888678 -0.11813384
  -0.01816035]
 [-0.00303013  0.06360614 -0.08300201 ...  0.01151469  0.09402999
   0.00569238]
 [-0.03433533 -0.06545837  0.0213762  ... -0.07824856  0.01055485
  -0.01312909]]


In [ ]:
tokenizer.texts_to_sequences(['manh'])

[[1]]

In [ ]:
weights[1]

array([-0.02560235,  0.011722  ,  0.02681784, -0.00128659,  0.01188255,
       -0.06271215, -0.04128057, -0.02775746, -0.02864632,  0.02226432,
        0.00111985,  0.02488773, -0.05193757,  0.07320369, -0.00359536,
       -0.0263497 ,  0.05071015,  0.07836451, -0.00698289,  0.00679792,
        0.00348576,  0.02208068,  0.03949107,  0.02535065,  0.02083684,
        0.03904153,  0.03469598,  0.01901636,  0.01294028,  0.01244821,
        0.002118  , -0.00345879,  0.04462634, -0.00286979, -0.02095976,
       -0.00728133, -0.00424781, -0.01854956, -0.06924158, -0.02791968,
       -0.02805555,  0.01936739, -0.00213806,  0.00223791, -0.00207123,
       -0.01650931,  0.02660527,  0.02623262, -0.02814359,  0.01344503,
        0.00470695,  0.00434358,  0.0132109 ,  0.02987109,  0.0052778 ,
        0.00349979,  0.00802857,  0.0490417 , -0.0346121 ,  0.02558849,
       -0.02574337, -0.01761917,  0.0136407 , -0.01606897], dtype=float32)

In [ ]:
import io
out_v = io.open('vecs.tsv', 'w', encoding='utf-8')
out_m = io.open('meta.tsv', 'w', encoding='utf-8')

for idx in range(1, vocab_size):
  word = tokenizer.index_word[idx]
  vector = weights[idx]
  out_m.write(word + '\n')
  out_v.write('\t'.join([str(x) for x in vector]) + '\n')
out_m.close()
out_v.close()